spring:

  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/todolist # 데이터베이스 URL
    username: ${DB_USERNAME:your_username} # 데이터베이스 사용자 이름
    password: ${DB_PASSWORD:your_password} # 데이터베이스 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REDIS_HOST:localhost} # Redis 호스트
    port: ${REDIS_PORT:6379} # Redis 포트

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  jwt:
    secret: ${JWT_SECRET:your_jwt_secret} # JWT 비밀 키

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your_google_client_id} # Google 클라이언트 ID
            client-secret: ${GOOGLE_CLIENT_SECRET:your_google_client_secret} # Google 클라이언트 비밀
            scope:
              - profile
              - email

          facebook:
            client-id: ${FACEBOOK_CLIENT_ID:your_facebook_client_id} # Facebook 클라이언트 ID
            client-secret: ${FACEBOOK_CLIENT_SECRET:your_facebook_client_secret} # Facebook 클라이언트 비밀
            scope:
              - public_profile
              - email

          naver:
            client-id: ${NAVER_CLIENT_ID:your_naver_client_id} # Naver 클라이언트 ID
            client-secret: ${NAVER_CLIENT_SECRET:your_naver_client_secret} # Naver 클라이언트 비밀
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: ${NAVER_REDIRECT_URI:http://localhost:8080/login/oauth2/code/naver} # 리디렉션 URI

        provider:
          naver:
            authorization-uri: ${NAVER_AUTHORIZATION_URI} # Naver 인증 URI
            token-uri: ${NAVER_TOKEN_URI} # Naver 토큰 URI
            user-info-uri: ${NAVER_USER_INFO_URI} # Naver 사용자 정보 URI
            user-name-attribute: response # 사용자 정보를 포함하는 키

logging.level:
  com.acoldbottle.todolist.jwt: warn
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
